//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AmulenEntities : DbContext
    {
        public AmulenEntities()
            : base("name=AmulenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HomePageData> HomePageData { get; set; }
        public virtual DbSet<HomePageImage> HomePageImage { get; set; }
        public virtual DbSet<Proyect> Proyect { get; set; }
        public virtual DbSet<ProyectState> ProyectState { get; set; }
        public virtual DbSet<SuscriptorProyect> SuscriptorProyect { get; set; }
        public virtual DbSet<TypeUser> TypeUser { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
