//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePageData
    {
        public int id { get; set; }
        public string WelcomeText { get; set; }
        public System.DateTime editDate { get; set; }
        public int UserId { get; set; }
    }
}
