//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int id { get; set; }
        public string title { get; set; }
        public string post_content { get; set; }
        public string image { get; set; }
        public byte id_category { get; set; }
        public System.DateTime creation_date { get; set; }
        public bool is_active { get; set; }
    
        public virtual category category { get; set; }
    }
}
