//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyect
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyect()
        {
            this.SuscriptorProyect = new HashSet<SuscriptorProyect>();
        }
    
        public int id { get; set; }
        public string proyectName { get; set; }
        public string proyectDetail { get; set; }
        public System.DateTime editDate { get; set; }
        public int StateId { get; set; }
        public int UserStateId { get; set; }
    
        public virtual ProyectState ProyectState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuscriptorProyect> SuscriptorProyect { get; set; }
    }
}
