//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuscriptorProyect
    {
        public int id { get; set; }
        public int ProyectId { get; set; }
        public int UserId { get; set; }
        public bool isActive { get; set; }
    
        public virtual Proyect Proyect { get; set; }
        public virtual User User { get; set; }
    }
}
