//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuscriptorProyect
    {
        public int id { get; set; }
        public int ProyectId { get; set; }
        public int UserId { get; set; }
        public bool isActive { get; set; }
    
        public virtual Proyect Proyect { get; set; }
        public virtual User User { get; set; }
    }
}
