//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.SuscriptorProyect = new HashSet<SuscriptorProyect>();
        }
    
        public int id { get; set; }
        [Required]
        [DisplayName(displayName: "Nombre")]
        public string name { get; set; }
        [DisplayName(displayName: "Correo electrónico")]
        [Required]
        public string email { get; set; }
        [Required]
        [DisplayName(displayName: "Usuario")]
        public string username { get; set; }
        [DisplayName(displayName: "Contraseña")]
        public string pass { get; set; }
        [DisplayName(displayName: "Tipo de usuario")]
        public int typeUserId { get; set; }
        [DisplayName(displayName: "Usuario activo")]
        public bool isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuscriptorProyect> SuscriptorProyect { get; set; }
        public virtual TypeUser TypeUser { get; set; }
    }
}
